/**
 * Portfolio Guide — Worker entrypoint (phase 1 scaffold).
 *
 * Live surface is intentionally thin: /health reports readiness, every other
 * route returns 501 until retrieval + chat land. The corpus contract lives in
 * the site's src/lib/guide/ module; ingestion, GuardEval checks, and the
 * session DO logic arrive in the next phases.
 *
 * Env is generated by `wrangler types` — see worker-configuration.d.ts.
 */
import { DurableObject } from "cloudflare:workers";

/** One DO per anonymous chat session — short-lived, no retention. */
export class GuideSession extends DurableObject<Env> {
  async fetch(_request: Request): Promise<Response> {
    return Response.json(
      { error: "chat not implemented — phase 1 scaffold" },
      { status: 501 },
    );
  }

  /** Alarm-based expiry so sessions never outlive SESSION_TTL_SECONDS. */
  async alarm(): Promise<void> {
    await this.ctx.storage.deleteAll();
  }
}

export default {
  async fetch(request: Request): Promise<Response> {
    const url = new URL(request.url);

    if (url.pathname === "/health") {
      return Response.json({ ok: true, service: "portfolio-guide" });
    }

    // Chat/retrieval land in later phases; fail closed everywhere else.
    return Response.json(
      { error: "not implemented — phase 1 scaffold" },
      { status: 501 },
    );
  },
} satisfies ExportedHandler<Env>;
